[program:redis]
command=/opt/redis-4.0.1/src/redis-server
user=root
numprocs=1
directory=/opt/redis-4.0.1/src/
stdout_logfile=/var/log/redis_access.log
stderr_logfile=/var/log/redis_error.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 120
priority=998



[program:djangoproject.celeryd]
command=celery -A cmdb worker -c 4 --loglevel=info
user=root
numprocs=1
directory=/root/cmdb
stdout_logfile=/var/log/celery_worker_access.log
stderr_logfile=/var/log/celery_worker-error.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 120
priority=998

[program:djangoproject.celerybeat]
command=celery -A cmdb beat --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid --loglevel=INFO
user=root
numprocs=1
directory=/root/cmdb
stdout_logfile=/var/log/celery_beat_access.log
stderr_logfile=/var/log/celery_beat_error.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 120
priority=998

# celery 5 移除了 celerycam 事件监听命令，如需监控可用 `celery -A cmdb events`


[program:djangoproject.celeryflower]
command=celery -A cmdb flower --port=9008
user=root
numprocs=1
directory=/root/cmdb
stdout_logfile=/var/log/celerycam_access.log
stderr_logfile=/var/log/celerycam_error.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 120
priority=998