# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='out_use',
        ),
    ]
